# eve_to_csv.py
"""
Offline helper script:
- Input : Suricata eve.json (with flow events)
- Output: CSV with UNSW-like feature columns
         proto, service, spkts, dpkts, sbytes, dbytes, dur
"""

import argparse
import json
import pandas as pd
from pathlib import Path


FEATURE_COLS = ["proto", "service", "spkts", "dpkts", "sbytes", "dbytes", "dur"]


def parse_args():
    p = argparse.ArgumentParser(
        description="Convert Suricata eve.json (flow events) to UNSW-style features CSV."
    )
    p.add_argument(
        "--eve",
        "-e",
        required=True,
        help="Path to eve.json generated by Suricata",
    )
    p.add_argument(
        "--out",
        "-o",
        required=True,
        help="Output CSV path for features (e.g. data/suricata_flows.csv)",
    )
    return p.parse_args()


def eve_to_df(eve_path: str) -> pd.DataFrame:
    rows = []
    eve_path = Path(eve_path)

    with eve_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue

            if rec.get("event_type") != "flow":
                continue

            flow = rec.get("flow", {}) or {}

            proto = rec.get("proto", "unknown")
            service = rec.get("app_proto", "unknown")

            spkts = flow.get("pkts_toserver", 0)
            dpkts = flow.get("pkts_toclient", 0)
            sbytes = flow.get("bytes_toserver", 0)
            dbytes = flow.get("bytes_toclient", 0)
            dur = flow.get("duration", 0.0)

            rows.append(
                {
                    "proto": proto,
                    "service": service,
                    "spkts": spkts,
                    "dpkts": dpkts,
                    "sbytes": sbytes,
                    "dbytes": dbytes,
                    "dur": dur,
                }
            )

    if not rows:
        raise RuntimeError(f"No flow events found in {eve_path}")

    df = pd.DataFrame(rows, columns=FEATURE_COLS)

    # enforce dtypes
    df["proto"] = df["proto"].astype(str)
    df["service"] = df["service"].astype(str)
    for col in ["spkts", "dpkts", "sbytes", "dbytes"]:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype("int64")
    df["dur"] = pd.to_numeric(df["dur"], errors="coerce").fillna(0.0).astype("float64")

    return df


def main():
    args = parse_args()

    df = eve_to_df(args.eve)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    df.to_csv(out_path, index=False)
    print(f"[OK] Wrote {len(df)} flows to: {out_path}")
    print("[OK] Columns:", ", ".join(df.columns))


if __name__ == "__main__":
    main()
