# eve_to_rest.py
"""
Online helper script:
- Input : Suricata eve.json (flow events)
- For each flow, send a REST request to the FastAPI ML server
- Collect and show a small summary of predictions

Assumes FastAPI server has:
  POST /predict_one
  Body:
    {
      "proto": "...",
      "service": "...",
      "spkts": int,
      "dpkts": int,
      "sbytes": int,
      "dbytes": int,
      "dur": float
    }
  Response (example):
    {
      "bin_label": "attack" | "normal",
      "dos_vs_other_label": "dos" | "other_attack" | null,
      "final_label": "normal" | "dos" | "other_attack"
    }
"""

import argparse
import json
from pathlib import Path
from collections import Counter

import requests


def parse_args():
    p = argparse.ArgumentParser(
        description="Stream Suricata eve.json flow events to ML REST server."
    )
    p.add_argument(
        "--eve",
        "-e",
        required=True,
        help="Path to eve.json generated by Suricata",
    )
    p.add_argument(
        "--url",
        "-u",
        default="http://127.0.0.1:8000",
        help="Base URL of REST server (default: http://127.0.0.1:8000)",
    )
    p.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional max number of flows to send (for testing)",
    )
    return p.parse_args()


def iter_flow_events(eve_path: Path):
    with eve_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue

            if rec.get("event_type") != "flow":
                continue

            yield rec


def main():
    args = parse_args()
    eve_path = Path(args.eve)
    base_url = args.url.rstrip("/")

    url_predict = f"{base_url}/predict_one"

    counts = Counter()
    total = 0

    for i, rec in enumerate(iter_flow_events(eve_path)):
        if args.limit is not None and i >= args.limit:
            break

        flow = rec.get("flow", {}) or {}

        payload = {
            "proto": rec.get("proto", "unknown"),
            "service": rec.get("app_proto", "unknown"),
            "spkts": flow.get("pkts_toserver", 0),
            "dpkts": flow.get("pkts_toclient", 0),
            "sbytes": flow.get("bytes_toserver", 0),
            "dbytes": flow.get("bytes_toclient", 0),
            "dur": flow.get("duration", 0.0),
        }

        try:
            resp = requests.post(url_predict, json=payload, timeout=5)
            resp.raise_for_status()
            data = resp.json()
        except Exception as e:
            print(f"[WARN] Error calling REST API for flow #{i}: {e}")
            continue

        final_label = data.get("final_label", "unknown")
        counts[final_label] += 1
        total += 1

        # For debugging, print first few
        if i < 5:
            print(f"[DEBUG] Flow #{i} request: {payload}")
            print(f"[DEBUG] Flow #{i} response: {data}")

    print("\n[SUMMARY] REST predictions:")
    print(f"Total flows sent: {total}")
    for label, c in counts.most_common():
        print(f"  {label:12s}: {c}")


if __name__ == "__main__":
    main()
